export type PlanningSourceSeed = {
  sourceKey: string;
  sourceName: string;
  category: string;
  authorityName: string;
  publicUrl: string;
  serviceUrl: string | null;
  serviceType:
    | "PUBLIC_VIEWER"
    | "DOCUMENT_URL"
    | "CLIENT_UPLOAD"
    | "PAID_DOCUMENT";
  isOfficial: boolean;
  isPaid: boolean;
  integrationStatus:
    | "connected"
    | "requires_service_discovery"
    | "manual_or_paid_order"
    | "manual_upload";
  notes: string;
};

export const PLANNING_SOURCE_SEEDS: PlanningSourceSeed[] = [
  {
    sourceKey: "NSW_PLANNING_PORTAL",
    sourceName: "NSW Planning Portal",
    category: "planning",
    authorityName: "NSW Government",
    publicUrl: "https://www.planningportal.nsw.gov.au/",
    serviceUrl: null,
    serviceType: "PUBLIC_VIEWER",
    isOfficial: true,
    isPaid: false,
    integrationStatus: "requires_service_discovery",
    notes: "Official landing page. Record and test an authorised service URL separately.",
  },
  {
    sourceKey: "NSW_PLANNING_SPATIAL_VIEWER",
    sourceName: "NSW Planning Portal Spatial Viewer",
    category: "planning_spatial",
    authorityName: "NSW Government",
    publicUrl: "https://www.planningportal.nsw.gov.au/spatialviewer/",
    serviceUrl: null,
    serviceType: "PUBLIC_VIEWER",
    isOfficial: true,
    isPaid: false,
    integrationStatus: "requires_service_discovery",
    notes: "Mapped information is not survey-accurate. Do not scrape the viewer.",
  },
  {
    sourceKey: "NSW_LEGISLATION",
    sourceName: "NSW Legislation",
    category: "legislation",
    authorityName: "NSW Government",
    publicUrl: "https://legislation.nsw.gov.au/",
    serviceUrl: null,
    serviceType: "DOCUMENT_URL",
    isOfficial: true,
    isPaid: false,
    integrationStatus: "requires_service_discovery",
    notes: "Store instrument, clause, version, effective date and exact source URL.",
  },
  {
    sourceKey: "NSW_SPATIAL_COLLABORATION_PORTAL",
    sourceName: "NSW Spatial Collaboration Portal",
    category: "spatial",
    authorityName: "NSW Government",
    publicUrl: "https://portal.spatial.nsw.gov.au/",
    serviceUrl: null,
    serviceType: "PUBLIC_VIEWER",
    isOfficial: true,
    isPaid: false,
    integrationStatus: "requires_service_discovery",
    notes: "Discovery point for licensed spatial services and datasets.",
  },
  {
    sourceKey: "NSW_SIX_MAPS",
    sourceName: "SIX Maps",
    category: "spatial_verification",
    authorityName: "NSW Government",
    publicUrl: "https://maps.six.nsw.gov.au/",
    serviceUrl: null,
    serviceType: "PUBLIC_VIEWER",
    isOfficial: true,
    isPaid: false,
    integrationStatus: "requires_service_discovery",
    notes: "Use for human verification unless an authorised data service is recorded.",
  },
  {
    sourceKey: "NSW_SPATIAL_SERVICES",
    sourceName: "NSW Spatial Services",
    category: "property",
    authorityName: "NSW Government",
    publicUrl: "https://www.spatial.nsw.gov.au/",
    serviceUrl: null,
    serviceType: "DOCUMENT_URL",
    isOfficial: true,
    isPaid: false,
    integrationStatus: "requires_service_discovery",
    notes: "Property, parcel, survey and mapping products.",
  },
  {
    sourceKey: "NSW_LAND_REGISTRY_SERVICES",
    sourceName: "NSW Land Registry Services",
    category: "title",
    authorityName: "NSW Land Registry Services",
    publicUrl: "https://www.nswlrs.com.au/",
    serviceUrl: null,
    serviceType: "PAID_DOCUMENT",
    isOfficial: true,
    isPaid: true,
    integrationStatus: "manual_or_paid_order",
    notes: "Title, deposited-plan and registered-interest documents may require purchase.",
  },
  {
    sourceKey: "CLIENT_OR_SURVEYOR_SURVEY",
    sourceName: "Registered detail survey",
    category: "survey",
    authorityName: "Client or registered surveyor",
    publicUrl: "https://www.bossi.nsw.gov.au/",
    serviceUrl: null,
    serviceType: "CLIENT_UPLOAD",
    isOfficial: false,
    isPaid: true,
    integrationStatus: "manual_upload",
    notes: "Keep surveyed area separate from mapped and title areas.",
  },
  {
    sourceKey: "NSW_RFS",
    sourceName: "NSW Rural Fire Service",
    category: "bushfire",
    authorityName: "NSW Rural Fire Service",
    publicUrl: "https://www.rfs.nsw.gov.au/",
    serviceUrl: null,
    serviceType: "DOCUMENT_URL",
    isOfficial: true,
    isPaid: false,
    integrationStatus: "requires_service_discovery",
    notes: "A mapped bushfire flag is screening, not a detailed bushfire assessment.",
  },
  {
    sourceKey: "NSW_SEED_DATA_PORTAL",
    sourceName: "NSW SEED data portal",
    category: "environment",
    authorityName: "NSW Government",
    publicUrl: "https://datasets.seed.nsw.gov.au/",
    serviceUrl: null,
    serviceType: "PUBLIC_VIEWER",
    isOfficial: true,
    isPaid: false,
    integrationStatus: "requires_service_discovery",
    notes: "Review dataset date, licence, coverage and schema before integration.",
  },
  {
    sourceKey: "NSW_HERITAGE",
    sourceName: "NSW Heritage",
    category: "heritage",
    authorityName: "NSW Government",
    publicUrl: "https://www.environment.nsw.gov.au/topics/heritage",
    serviceUrl: null,
    serviceType: "DOCUMENT_URL",
    isOfficial: true,
    isPaid: false,
    integrationStatus: "requires_service_discovery",
    notes: "Cross-check State, LEP and Council heritage records.",
  },
  {
    sourceKey: "NSW_EPA_CONTAMINATED_LAND",
    sourceName: "NSW EPA contaminated land",
    category: "contamination",
    authorityName: "NSW Environment Protection Authority",
    publicUrl: "https://www.epa.nsw.gov.au/your-environment/contaminated-land",
    serviceUrl: null,
    serviceType: "DOCUMENT_URL",
    isOfficial: true,
    isPaid: false,
    integrationStatus: "requires_service_discovery",
    notes: "No public listing is not proof that land is uncontaminated.",
  },
  {
    sourceKey: "NSW_BASIX",
    sourceName: "BASIX",
    category: "project_document",
    authorityName: "NSW Government",
    publicUrl: "https://www.planningportal.nsw.gov.au/basix",
    serviceUrl: null,
    serviceType: "CLIENT_UPLOAD",
    isOfficial: true,
    isPaid: false,
    integrationStatus: "manual_upload",
    notes: "Project commitments must come from the issued certificate.",
  },
  {
    sourceKey: "BEFORE_YOU_DIG_AUSTRALIA",
    sourceName: "Before You Dig Australia",
    category: "services",
    authorityName: "Before You Dig Australia",
    publicUrl: "https://www.byda.com.au/",
    serviceUrl: null,
    serviceType: "DOCUMENT_URL",
    isOfficial: false,
    isPaid: false,
    integrationStatus: "manual_upload",
    notes: "Returned plans are project documents requiring review.",
  },
  {
    sourceKey: "NSW_SECTION_10_7_CERTIFICATE",
    sourceName: "Section 10.7 planning certificate",
    category: "statutory_certificate",
    authorityName: "Relevant NSW local council",
    publicUrl: "https://www.service.nsw.gov.au/transaction/apply-online-for-a-planning-certificate",
    serviceUrl: null,
    serviceType: "PAID_DOCUMENT",
    isOfficial: true,
    isPaid: true,
    integrationStatus: "manual_or_paid_order",
    notes: "Council-issued evidence. Requires a client/council application and fee or an authorised client upload; never synthesize a replacement.",
  },
  {
    sourceKey: "NSW_BIODIVERSITY_VALUES_MAP",
    sourceName: "Biodiversity Values Map and Threshold Tool",
    category: "biodiversity",
    authorityName: "NSW Department of Climate Change, Energy, the Environment and Water",
    publicUrl: "https://www.environment.nsw.gov.au/topics/animals-and-plants/biodiversity-offsets-scheme/clear-and-develop-land/biodiversity-values-map-and-threshold-tool",
    serviceUrl: null,
    serviceType: "PUBLIC_VIEWER",
    isOfficial: true,
    isPaid: false,
    integrationStatus: "requires_service_discovery",
    notes: "A project footprint is required for a threshold report; property-only screening cannot determine the final trigger.",
  },
  {
    sourceKey: "SYDNEY_WATER_TAP_IN",
    sourceName: "Sydney Water Tap in",
    category: "water_sewer_services",
    authorityName: "Sydney Water",
    publicUrl: "https://www.sydneywater.com.au/plumbing-building-developing/building/sydney-water-tap-in.html",
    serviceUrl: null,
    serviceType: "PAID_DOCUMENT",
    isOfficial: true,
    isPaid: true,
    integrationStatus: "manual_or_paid_order",
    notes: "Order service-location, wastewater or asset diagrams where Sydney Water is the authority. Use the applicable regional utility elsewhere.",
  },
  {
    sourceKey: "NSW_VALUER_GENERAL",
    sourceName: "NSW land values and property information",
    category: "land_value",
    authorityName: "Valuer General NSW",
    publicUrl: "https://www.nsw.gov.au/housing-and-construction/land-values-nsw/how-to-find-land-values-nsw",
    serviceUrl: null,
    serviceType: "DOCUMENT_URL",
    isOfficial: true,
    isPaid: false,
    integrationStatus: "manual_upload",
    notes: "Land value is decision context, not a planning entitlement or a valuation of proposed development returns.",
  },
  {
    sourceKey: "PROJECT_ARCHITECTURAL_PLANS",
    sourceName: "Architectural plans",
    category: "project_document",
    authorityName: "FRC, external architect or client",
    publicUrl: "https://frcdc.com.au/",
    serviceUrl: null,
    serviceType: "CLIENT_UPLOAD",
    isOfficial: false,
    isPaid: false,
    integrationStatus: "manual_upload",
    notes: "Store author, drawing number, revision, issue date and approval status.",
  },
];
